name: deploy-online-endpoint-pipeline

on:
  push:
  workflow_dispatch:

jobs:
  set-env:
    runs-on: ubuntu-latest
    outputs:
      config-file: ${{ steps.set-output-defaults.outputs.config-file }}
    steps:
      - id: set-prod-branch
        name: Set prod branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "config_env=config-infra-prod.yml" >> "$GITHUB_ENV"

      - id: set-dev-branch
        name: Set dev branch
        if: ${{ github.ref != 'refs/heads/main' }}
        run: echo "config_env=config-infra-dev.yml" >> "$GITHUB_ENV"

      - id: set-output-defaults
        name: Set output defaults
        run: echo "config-file=$config_env" >> "$GITHUB_OUTPUT"

  parse-config:
    needs: set-env
    runs-on: ubuntu-latest
    outputs:
      resource_group: ${{ steps.config.outputs.resource_group }}
      aml_workspace: ${{ steps.config.outputs.aml_workspace }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Parse config
        id: config
        uses: ./.github/actions/parse-config
        with:
          config-file: ${{ needs.set-env.outputs.config-file }}

  deploy:
    needs: [set-env, parse-config]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Azure Login (OIDC)
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Create online endpoint
        run: |
          az ml online-endpoint create \
            --file mlops/azureml/deploy/online/online-endpoint.yml \
            --name taxi-online-endpoint \
            --resource-group ${{ needs.parse-config.outputs.resource_group }} \
            --workspace-name ${{ needs.parse-config.outputs.aml_workspace }} \
            || true

      - name: Create online deployment
        run: |
          az ml online-deployment create \
            --file mlops/azureml/deploy/online/online-deployment.yml \
            --endpoint-name taxi-online-endpoint \
            --resource-group ${{ needs.parse-config.outputs.resource_group }} \
            --workspace-name ${{ needs.parse-config.outputs.aml_workspace }} \
            --all-traffic

      - name: Allocate traffic
        run: |
          az ml online-endpoint update \
            --name taxi-online-endpoint \
            --traffic "blue=100" \
            --resource-group ${{ needs.parse-config.outputs.resource_group }} \
            --workspace-name ${{ needs.parse-config.outputs.aml_workspace }}
